### ISSUE TITLE
When explorer.exe crashes and restarts the tray icon is gone

### ISSUE THREAD

**Issue by udany** [diogoalmiro/ctray#8]
First off, thanks for the work on this, srsly ♥

Now, on to the issue: If explorer.exe has to restart the tray icon will be gone and there's no way to know this within node afaik, looking around all I could find is [this meager forum thread from 2004](https://forums.codeguru.com/showthread.php?303732-to-recreate-the-system-tray-icon-when-explorer-crashes) which I don't think I quite understand...

Do you have any idea if this is fixable?

**Comment by diogoalmiro** [comment]
Hi, thanks for the issue!
It seems fixable according to [answer 5 of that thread](https://forums.codeguru.com/showthread.php?303732-to-recreate-the-system-tray-icon-when-explorer-crashes&p=986013#post986013).
I will be working on [improving the menu handling](https://github.com/diogoalmiro/ctray/tree/5-improve-menu), which will make me understand better the windows.h API during November. I will try to handle this issue on that update.

**Comment by udany** [comment]
Thank you, it worked ♥ ♥ ♥
